// Content for the renovation journal — EN + NL.
// Captions are drafts the user will edit. The structure is intentionally flat
// so the user can edit any string in the file directly.

window.CONTENT = {
  en: {
    site: {
      title: "Apartment renovation",
      legendLabel: "Phases",
      lastUpdated: "Last updated",
      lastUpdatedDate: "May 2026",
      currentlyAt: "Currently at phase 05 — plasterboard",
      languageLabel: "Language",
      phaseLabel: "Phase",
      ofLabel: "of",
      workInProgress: "Work in progress",
    },
    phases: [
      {
        id: "original",
        short: "Starting phase",
        full: "Starting phase",
        n: "01",
        chip: "Start",
        date: "November 2025",
      },
      {
        id: "stripped",
        short: "Stripped",
        full: "Stripped",
        n: "02",
        chip: "Stripped",
        date: "",
      },
      {
        id: "diy-insulation",
        short: "DIY insulation",
        full: "Inside insulation (DIY)",
        n: "03",
        chip: "Insulation · me",
        date: "",
      },
      {
        id: "wall-pro",
        short: "Outer wall",
        full: "Outer wall insulation (pro)",
        n: "04",
        chip: "Outer wall · pro",
        date: "",
      },
      {
        id: "plasterboard",
        short: "Plasterboard",
        full: "Plasterboard (pro)",
        n: "05",
        chip: "Plasterboard · pro",
        date: "May 2026",
      },
      {
        id: "ceiling",
        short: "Ceiling",
        full: "Ceiling plasterboard (me)",
        n: "06",
        chip: "Ceiling · me",
        date: "",
        future: true,
      },
    ],
    rooms: [
      {
        id: "kitchen",
        n: "01",
        name: "Kitchen",
        aspect: "4 / 3",
        captions: ["", "", "", "", "", ""],
        images: ["photos/kitchen-1.jpg", "photos/kitchen-2.jpg", "photos/kitchen-3.jpg", "photos/kitchen-4.jpg", "photos/kitchen-5.jpg", "photos/kitchen-6.jpg"],
      },
      {
        id: "bathroom",
        n: "02",
        name: "Bathroom",
        aspect: "4 / 3",
        captions: ["", "", "", "", "", ""],
        images: ["photos/bathroom-1.jpg", "photos/bathroom-2.jpg", "photos/bathroom-3.jpg", "photos/bathroom-4.jpg", "photos/bathroom-5.jpg", "photos/bathroom-6.jpg"],
      },
      {
        id: "bedroom",
        n: "03",
        name: "Bedroom",
        aspect: "4 / 3",
        captions: ["", "", "", "", "", ""],
        images: ["photos/bedroom-1.jpg", "photos/bedroom-2.jpg", "photos/bedroom-3.jpg", "photos/bedroom-4.jpg", "photos/bedroom-5.jpg", "photos/bedroom-6.jpg"],
      },
      {
        id: "living-room",
        n: "04",
        name: "Living Room",
        aspect: "16 / 10",
        captions: ["", "", "", "", "", ""],
        images: ["photos/living-room-1.jpg", "photos/living-room-2.jpg", "photos/living-room-3.jpg", "photos/living-room-4.jpg", "photos/living-room-5.jpg", "photos/living-room-6.jpg"],
      },
      {
        id: "office",
        n: "05",
        name: "Office Corner",
        aspect: "4 / 3",
        captions: ["", "", "", "", "", ""],
        images: ["photos/office-1.jpg", "photos/office-2.jpg", "photos/office-3.jpg", "photos/office-4.jpg", "photos/office-5.jpg", "photos/office-6.jpg"],
      },
    ],
  },
  nl: {
    site: {
      title: "Appartement renovatie",
      legendLabel: "Fases",
      lastUpdated: "Laatst bijgewerkt",
      lastUpdatedDate: "mei 2026",
      currentlyAt: "Nu in fase 05 — gipsplaten",
      languageLabel: "Taal",
      phaseLabel: "Fase",
      ofLabel: "van",
      workInProgress: "Werk in uitvoering",
    },
    phases: [
      {
        id: "original",
        short: "Beginfase",
        full: "Beginfase",
        n: "01",
        chip: "Start",
        date: "november 2025",
      },
      {
        id: "stripped",
        short: "Gesloopt",
        full: "Gesloopt",
        n: "02",
        chip: "Gesloopt",
        date: "",
      },
      {
        id: "diy-insulation",
        short: "Isolatie (zelf)",
        full: "Binnenisolatie (zelf)",
        n: "03",
        chip: "Isolatie · zelf",
        date: "",
      },
      {
        id: "wall-pro",
        short: "Buitenmuur",
        full: "Buitenmuurisolatie (vakman)",
        n: "04",
        chip: "Buitenmuur · pro",
        date: "",
      },
      {
        id: "plasterboard",
        short: "Gipsplaten",
        full: "Gipsplaten (vakman)",
        n: "05",
        chip: "Gipsplaten · pro",
        date: "mei 2026",
      },
      {
        id: "ceiling",
        short: "Plafond",
        full: "Gipsplaten plafond (zelf)",
        n: "06",
        chip: "Plafond · zelf",
        date: "",
        future: true,
      },
    ],
    rooms: [
      {
        id: "kitchen",
        n: "01",
        name: "Keuken",
        aspect: "4 / 3",
        captions: ["", "", "", "", "", ""],
        images: ["photos/kitchen-1.jpg", "photos/kitchen-2.jpg", "photos/kitchen-3.jpg", "photos/kitchen-4.jpg", "photos/kitchen-5.jpg", "photos/kitchen-6.jpg"],
      },
      {
        id: "bathroom",
        n: "02",
        name: "Badkamer",
        aspect: "4 / 3",
        captions: ["", "", "", "", "", ""],
        images: ["photos/bathroom-1.jpg", "photos/bathroom-2.jpg", "photos/bathroom-3.jpg", "photos/bathroom-4.jpg", "photos/bathroom-5.jpg", "photos/bathroom-6.jpg"],
      },
      {
        id: "bedroom",
        n: "03",
        name: "Slaapkamer",
        aspect: "4 / 3",
        captions: ["", "", "", "", "", ""],
        images: ["photos/bedroom-1.jpg", "photos/bedroom-2.jpg", "photos/bedroom-3.jpg", "photos/bedroom-4.jpg", "photos/bedroom-5.jpg", "photos/bedroom-6.jpg"],
      },
      {
        id: "living-room",
        n: "04",
        name: "Woonkamer",
        aspect: "16 / 10",
        captions: ["", "", "", "", "", ""],
        images: ["photos/living-room-1.jpg", "photos/living-room-2.jpg", "photos/living-room-3.jpg", "photos/living-room-4.jpg", "photos/living-room-5.jpg", "photos/living-room-6.jpg"],
      },
      {
        id: "office",
        n: "05",
        name: "Werkhoek",
        aspect: "4 / 3",
        captions: ["", "", "", "", "", ""],
        images: ["photos/office-1.jpg", "photos/office-2.jpg", "photos/office-3.jpg", "photos/office-4.jpg", "photos/office-5.jpg", "photos/office-6.jpg"],
      },
    ],
  },
};
